language: node_js
sudo: false
os:
  - linux
node_js:
  - '7'
  - '8'
  - 'stable'
script:
  - npm run lint
  - npm run test:all
before_install:
- export TZ=Europe/Stockholm
notifications:
  email: false
